import type { Metadata } from "next";
import { Suspense } from "react";
import Footer from "../components/Footer/Footer";
import Header from "../components/Header/Header";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthWrapper } from "../components/AuthProvider/AuthProvider";
import { Toaster } from "react-hot-toast";
import "../globals.css";
import ScrollToTop from "app/dashboard/ScrollToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Richfield Farm and Smoke House LTD",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <head>
        {/* GIS script */}
        <script
          src="https://accounts.google.com/gsi/client"
          async
          defer
        ></script>
      </head>

      <Suspense>
        <body>
          <Toaster position="top-right" reverseOrder={false} />
          <AuthWrapper>
            <Header />
            <ScrollToTop />
            {children}
            <Footer />
          </AuthWrapper>
        </body>
      </Suspense>
    </html>
  );
}
