// app/layout.tsx or app/layout.tsx (depending on your structure)

import type { Metadata } from "next";
import Footer from "../components/Footer/Footer";
import Header from "../components/Header/Header";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthWrapper } from "../components/AuthProvider/AuthProvider";
import {Toaster} from "react-hot-toast";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Richfield Farm and Smoke House LTD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <Toaster position="top-right" reverseOrder={false} />
        <AuthWrapper>
          <Header />
          {children}
          <Footer />
        </AuthWrapper>
      </body>
    </html>
  );
}
