// app/layout.tsx or app/layout.tsx (depending on your structure)

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { AuthWrapper } from "../components/AuthProvider/AuthProvider";
import Sidebar from './components/sidebar/Sidebar'; // your custom components
import Navbar from './components/navbar/Navbar';
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <Toaster position="top-right" reverseOrder={false} />
        <AuthWrapper>
          <Sidebar/>
          <div className="flex-1 w-full min-h-screen overflow-y-auto">
            <Navbar/>
            {/* <TestToast/> */}
            <div className="p-6 bg-gray-50 min-h-screen ml-40">
              {children}
            </div>
          </div>
        </AuthWrapper>
      </body>
    </html>
  );
}
